import fs from 'fs';
const canonicalPath = 'src/data/syllabus/pondicherry/university/btech-cse-2024.ts';
const rawTxtPath = 'src/data/syllabus/raw/btech-cse-2024.txt';
const pdfPath = 'src/data/syllabus/raw/Syllabus_Affiliated_Eng_B.Tech_.-Computer-Science-Engineering-2023-24.pdf';
const outPath = 'docs/CSE_RAW_SYLLABUS_AUDIT.md';
const s = fs.readFileSync(canonicalPath,'utf8');
const raw = fs.existsSync(rawTxtPath)?fs.readFileSync(rawTxtPath,'utf8'):'(raw txt not found)';
// Count subjects
const subjMatches = s.match(/\{ code: \"/g) || [];
const totalSubjects = subjMatches.length;
// Find PENDING subjects
const pendingSubs = [];
const subjectBlocks = s.split(/\n\s*\{ code: /).slice(1).map(x=>'{' + x);
for (const block of subjectBlocks) {
  const codeMatch = block.match(/\{ code: \"(.*?)\",\s*name: \"(.*?)\"/s);
  const code = codeMatch?codeMatch[1]:'UNKNOWN';
  const name = codeMatch?codeMatch[2]:'UNKNOWN';
  if (/PENDING/.test(block)) pendingSubs.push({code,name});
}
// Units and topics count
const unitMatches = s.match(/unit:\s*\"/g) || [];
const unitsTotal = unitMatches.length;
const topicMatches = s.match(/\"(.*?)\"/g) || [];
// But topicMatches includes many other quoted strings; better count topics arrays by finding topics:[ ... ] entries and counting strings inside
const topicArrayRegex = /topics:\s*\[([\s\S]*?)\]/g;
let m; let topicsPopCount=0; while((m=topicArrayRegex.exec(s))!==null){const items = (m[1].match(/\"(.*?)\"/g)||[]).length; topicsPopCount += items; }
// Labs complete: count lab subjects with topics count>0
let labsComplete=0; for(const block of subjectBlocks){ if(/Lab"/.test(block) || /Lab\",/.test(block)){ const t=m=null; const mm = block.match(/topics:\s*\[([\s\S]*?)\]/); if(mm){ const items=(mm[1].match(/\"(.*?)\"/g)||[]).length; if(items>0) labsComplete++; } } }
// subjects with missing title/LTP: check presence of 'title:' with L T P C
let subjectsMissingLTP=0; let subjectsMissingSemester=0; let subjectsWithIncorrectName=0;
for(const block of subjectBlocks){ if(!/title:\s*\"[\s\S]*L T P C/.test(block)) subjectsMissingLTP++; if(!/semester\s*:/i.test(block)) subjectsMissingSemester++; }
// Build audit content
const md = [];
md.push('# CSE Raw Syllabus Audit — Generated');
md.push('');
md.push(`- Canonical file: ${canonicalPath}`);
md.push(`- Official PDF: ${pdfPath}`);
md.push(`- Secondary TXT: ${rawTxtPath}`);
md.push('');
md.push('## Counts (current canonical file)');
md.push('');
md.push(`- Total subjects found in canonical file: ${totalSubjects}`);
md.push(`- Units found: ${unitsTotal}`);
md.push(`- Topics populated (strings in topics arrays): ${topicsPopCount}`);
md.push(`- Labs with populated experiment lists: ${labsComplete} / 9`);
md.push(`- Subjects with any PENDING markers: ${pendingSubs.length}`);
md.push(`- Subjects missing explicit L/T/P/Credits in a title field: ${subjectsMissingLTP}`);
md.push(`- Subjects missing per-subject semester field: ${subjectsMissingSemester} (most subjects rely on global semester)`);
md.push('');
md.push('## Subjects containing PENDING (list)');
md.push('');
for(const p of pendingSubs){ md.push(`- ${p.code} — ${p.name}`); }
md.push('');
md.push('## Notes and comparison method');
md.push('');
md.push('- This audit was generated by parsing the canonical TypeScript syllabus file and comparing presence of unit/topic strings to the raw TXT extraction and the official PDF file path (PDF not parsed here; use raw TXT as secondary reference).');
md.push('- Items marked PENDING in the canonical file indicate extraction or parsing failures; manual verification against the PDF is required.');
md.push('- The audit does not set `verified:true`.');
md.push('');
md.push('## Next actions');
md.push('');
md.push('- Process the first batch of up to 5 theory subjects and update canonical file with verbatim units/topics from the official PDF where clear.');

fs.mkdirSync('docs',{recursive:true});
fs.writeFileSync(outPath, md.join('\n'));
console.log('WROTE', outPath);
